### PR TITLE
Refactor for multiple devices

### PR DESCRIPTION
**Pull request by EpicKris**
- Updated schema for multiple devices
- Updated code for multiple devices
- Better solution for #5

### CODE REVIEW

**Comment by neilpatel121** [comment]
Is this a breaking change cause of the configuration? Does it require a major version change?

**Comment by neilpatel121** [comment]
Thanks for sorting out a single instance plugin

**Comment by EpicKris** [comment]
> Is this a breaking change cause of the configuration? Does it require a major version change?

No, this is not a breaking change, users using the existing configuration(s) will continue to work, if the new configuration is detected, then it will use that instead.

The schema update does mean that anyone using the existing configuration(s) will need use the new configuration, but *only* if they need to update their configuration.

**Comment by neilpatel121** [comment]
Hey Kris, please send me your npm id, so you can publish yourself

**Comment by EpicKris** [comment]
> Hey Kris, please send me your npm id, so you can publish yourself

`epickris`

**Comment by neilpatel121** [comment]
Hey Kris you should be able to Nom publish now

**Comment by EpicKris** [comment]
> Hey Kris you should be able to Nom publish now

I don't have access to the repository settings, could you add a new Repository Secret: https://github.com/neilpatel121/homebridge-skyq-tvremote/settings/secrets/actions/new

Name: `NPM_TOKEN`
Value: npm Automatation Access Token: https://www.npmjs.com/settings/neilpatel121/tokens/create

**Comment by neilpatel121** [comment]
Hey Kris,

Followed your instructions, this is done

Neil

**Comment by EpicKris** [comment]
> Hey Kris, Followed your instructions, this is done Neil
> […](#)

Hey Neil, great, you can now use GitHub releases to publish new versions, including betas, to npm.

**Comment by neilpatel121** [comment]
Nice one Kris, beats doing manual publish.. git deployment is new to me

**Comment by EpicKris** [comment]
> Nice one Kris, beats doing manual publish.. git deployment is new to me

Just ensure the `package.json` `version` has been updated to the correct value before creating a new release. 👍🏻

**Pull request merged**
